var Cesium = module.exports = {};
var requirejs = require('requirejs');
var async = require('async');
var q = require('q');

var compat = {
  'Core': [
//  'ArcGisImageServerTerrainProvider',
    'AssociativeArray',
    'AttributeCompression',
    'AxisAlignedBoundingBox',
    'BingMapsApi',
    'BoundingRectangle',
    'BoundingSphere',
    'BoxGeometry',
    'BoxOutlineGeometry',
    'Cartesian2',
    'Cartesian3',
    'Cartesian4',
    'Cartographic',
    'CatmullRomSpline',
//  'CesiumTerrainProvider',
    'CircleGeometry',
    'CircleOutlineGeometry',
    'Clock',
    'ClockRange',
    'ClockStep',
    'Color',
    'ColorGeometryInstanceAttribute',
    'ComponentDatatype',
    'CornerType',
    'CorridorGeometry',
    'CorridorGeometryLibrary',
    'CorridorOutlineGeometry',
    'Credit',
    'CubicRealPolynomial',
    'CylinderGeometry',
    'CylinderGeometryLibrary',
    'CylinderOutlineGeometry',
    'DefaultProxy',
    'DeveloperError',
    'EarthOrientationParameters',
    'EarthOrientationParametersSample',
    'EasingFunction',
    'EllipseGeometry',
    'EllipseGeometryLibrary',
    'EllipseOutlineGeometry',
    'Ellipsoid',
    'EllipsoidGeodesic',
    'EllipsoidGeometry',
    'EllipsoidOutlineGeometry',
    'EllipsoidTangentPlane',
    'EllipsoidTerrainProvider',
    'EllipsoidalOccluder',
    'EncodedCartesian3',
    'Event',
    'EventHelper',
    'ExtrapolationType',
    'FeatureDetection',
    'Fullscreen',
    'GeographicProjection',
    'GeographicTilingScheme',
    'Geometry',
    'GeometryAttribute',
    'GeometryAttributes',
    'GeometryInstance',
    'GeometryInstanceAttribute',
    'GeometryPipeline',
    'GeometryType',
    'GregorianDate',
    'HeightmapTerrainData',
    'HeightmapTessellator',
    'HermitePolynomialApproximation',
    'HermiteSpline',
    'Iau2000Orientation',
    'Iau2006XysData',
    'Iau2006XysSample',
    'IauOrientationAxes',
    'IauOrientationParameters',
    'IndexDatatype',
    'InterpolationAlgorithm',
    'Intersect',
    'IntersectionTests',
    'Intersections2D',
    'Interval',
    'Iso8601',
    'JulianDate',
    'KeyboardEventModifier',
    'LagrangePolynomialApproximation',
    'LeapSecond',
    'LinearApproximation',
    'LinearSpline',
    'MapProjection',
    'Math',
    'Matrix2',
    'Matrix3',
    'Matrix4',
    'NearFarScalar',
    'ObjectOrientedBoundingBox',
    'Occluder',
    'Packable',
    'PackableForInterpolation',
    'PinBuilder',
    'PixelFormat',
    'Plane',
    'PolygonGeometry',
    'PolygonGeometryLibrary',
    'PolygonHierarchy',
    'PolygonOutlineGeometry',
    'PolygonPipeline',
    'PolylineGeometry',
    'PolylinePipeline',
    'PolylineVolumeGeometry',
    'PolylineVolumeGeometryLibrary',
    'PolylineVolumeOutlineGeometry',
    'PrimitiveType',
    'QuadraticRealPolynomial',
    'QuantizedMeshTerrainData',
    'QuarticRealPolynomial',
    'Quaternion',
    'QuaternionSpline',
    'Queue',
    'Ray',
    'Rectangle',
    'RectangleGeometry',
    'RectangleGeometryLibrary',
    'RectangleOutlineGeometry',
    'ReferenceFrame',
    'RequestErrorEvent',
    'RuntimeError',
    'ScreenSpaceEventHandler',
    'ScreenSpaceEventType',
    'ShowGeometryInstanceAttribute',
    'Simon1994PlanetaryPositions',
    'SimplePolylineGeometry',
    'SphereGeometry',
    'SphereOutlineGeometry',
    'Spherical',
    'Spline',
    'TaskProcessor',
    'TerrainData',
    'TerrainMesh',
    'TerrainProvider',
    'TileProviderError',
    'TilingScheme',
    'TimeConstants',
    'TimeInterval',
    'TimeIntervalCollection',
    'TimeStandard',
    'Tipsify',
    'Transforms',
    'TridiagonalSystemSolver',
//  'VRTheWorldTerrainProvider',
    'VertexFormat',
    'Visibility',
    'WallGeometry',
    'WallGeometryLibrary',
    'WallOutlineGeometry',
    'WebMercatorProjection',
    'WebMercatorTilingScheme',
    'WindingOrder',
    'appendForwardSlash',
    'barycentricCoordinates',
    'binarySearch',
    'buildModuleUrl',
//  'cancelAnimationFrame',
    'clone',
    'combine',
    'createGuid',
    'defaultValue',
    'defineProperties',
    'defined',
    'deprecationWarning',
    'destroyObject',
    'formatError',
    'freezeObject',
    'getFilenameFromUri',
    'getImagePixels',
    'getTimestamp',
    'isArray',
    'isCrossOriginUrl',
    'isLeapYear',
    'jsonp',
    'loadArrayBuffer',
    'loadBlob',
    'loadImage',
    'loadImageViaBlob',
    'loadJson',
    'loadText',
    'loadWithXhr',
    'loadXML',
    'mergeSort',
    'objectToQuery',
    'parseResponseHeaders',
    'pointInsideTriangle',
    'queryToObject',
//  'requestAnimationFrame',
    'sampleTerrain',
    'subdivideArray',
//  'throttleRequestByServer',
    'wrapFunction',
    'writeTextToCanvas'
  ]
};
var sections = Object.keys(compat);

function loadSectionModules(section, callback) {
  var mods = compat[section];
  var modulePaths = mods.map(function(name) {
    return './Source/' + section + '/' + name;
  });
  
  requirejs.config({
    baseUrl: "."
  });

  requirejs(modulePaths, function() {
    var loadedModules = [].slice.call(arguments);

    // iterate through the arguments and patch into the Cesium global
    mods.forEach(function(name, index) {
      Cesium[name] = loadedModules[index];
    });

    callback();
  });
}

var deferred = q.defer();

Cesium.isReady = deferred.promise;
  
async.forEach(sections, loadSectionModules, function() {
  deferred.resolve();
});

 